// <auto-generated />
using DeerDiary_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DeerDiary_Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241031141712_CreateDB")]
    partial class CreateDB
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("DeerDiary_Backend.Models.JournalEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("JournalId")
                        .HasAnnotation("Relational:JsonPropertyName", "JournalId");

                    b.Property<string>("_date")
                        .HasColumnType("longtext")
                        .HasColumnName("JournalDate")
                        .HasAnnotation("Relational:JsonPropertyName", "JournalDate");

                    b.Property<int>("_randomquestionid")
                        .HasColumnType("int")
                        .HasColumnName("RandomQuestionId")
                        .HasAnnotation("Relational:JsonPropertyName", "RandomQuestionId");

                    b.Property<string>("_text")
                        .HasColumnType("longtext")
                        .HasColumnName("JournalText")
                        .HasAnnotation("Relational:JsonPropertyName", "JournalText");

                    b.Property<string>("_title")
                        .HasColumnType("longtext")
                        .HasColumnName("JournalTitle")
                        .HasAnnotation("Relational:JsonPropertyName", "JournalTitle");

                    b.Property<int>("_userid")
                        .HasColumnType("int")
                        .HasColumnName("UserId")
                        .HasAnnotation("Relational:JsonPropertyName", "UserId");

                    b.HasKey("Id");

                    b.HasIndex("_randomquestionid");

                    b.HasIndex("_userid");

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("DeerDiary_Backend.Models.RandomQuestion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("RandomQuestionId")
                        .HasAnnotation("Relational:JsonPropertyName", "RandomQuestionId");

                    b.Property<string>("_text")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("RandomQuestionText")
                        .HasAnnotation("Relational:JsonPropertyName", "RandomQuestionText");

                    b.HasKey("Id");

                    b.ToTable("RandomQuestions");
                });

            modelBuilder.Entity("DeerDiary_Backend.Models.Reply", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ReplyId")
                        .HasAnnotation("Relational:JsonPropertyName", "ReplyId");

                    b.Property<string>("_generatedquestion")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ReplyGeneratedQuestion")
                        .HasAnnotation("Relational:JsonPropertyName", "ReplyGeneratedQuestion");

                    b.Property<int>("_journalentryId")
                        .HasColumnType("int");

                    b.Property<string>("_journalentryid")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("JournalEntryId")
                        .HasAnnotation("Relational:JsonPropertyName", "JournalEntryId");

                    b.Property<string>("_text")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("ReplyText")
                        .HasAnnotation("Relational:JsonPropertyName", "ReplyText");

                    b.HasKey("Id");

                    b.HasIndex("_journalentryId");

                    b.ToTable("Replies");
                });

            modelBuilder.Entity("DeerDiary_Backend.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("UserId")
                        .HasAnnotation("Relational:JsonPropertyName", "UserId");

                    b.Property<string>("_usermail")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("UserMail")
                        .HasAnnotation("Relational:JsonPropertyName", "UserMail");

                    b.Property<string>("_username")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("UserName")
                        .HasAnnotation("Relational:JsonPropertyName", "UserName");

                    b.Property<string>("_userpassword")
                        .IsRequired()
                        .HasColumnType("longtext")
                        .HasColumnName("UserPassword")
                        .HasAnnotation("Relational:JsonPropertyName", "UserPassword");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DeerDiary_Backend.Models.JournalEntry", b =>
                {
                    b.HasOne("DeerDiary_Backend.Models.RandomQuestion", "_randomquestion")
                        .WithMany()
                        .HasForeignKey("_randomquestionid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DeerDiary_Backend.Models.User", "_user")
                        .WithMany()
                        .HasForeignKey("_userid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_randomquestion");

                    b.Navigation("_user");
                });

            modelBuilder.Entity("DeerDiary_Backend.Models.Reply", b =>
                {
                    b.HasOne("DeerDiary_Backend.Models.JournalEntry", "_journalentry")
                        .WithMany()
                        .HasForeignKey("_journalentryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("_journalentry");
                });
#pragma warning restore 612, 618
        }
    }
}
