name: Lint + Format + Test C# Code

on: [pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0'
      - run: dotnet restore
      - run: dotnet build --no-restore
      - run: dotnet format

  # test:
  #   runs-on: ubuntu-latest
  #   needs: lint 
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Set up .NET
  #       uses: actions/setup-dotnet@v1
  #       with:
  #         dotnet-version: '8.0'
  #     - run: dotnet restore
  #     - run: dotnet format
  #     - run: dotnet test --no-restore --verbosity normal